version: '3'

services:
  web:
    image: php:8.1-apache
    container_name: php-app
    volumes:
      - ./app:/var/www/html
    ports:
      - 8080:80
    networks:
      - mynetwork
    depends_on:
      - db

  db:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: mydatabase
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - mynetwork

networks:
  mynetwork:
